In [2]:
def gen(n):
    ans = []

    def f(s, o, c):
        if o == n and c == n:
            ans.append(s)
            return

        if o < n:
            f(s + "(", o + 1, c)

        if c < o:
            f(s + ")", o, c + 1)

    f("", 0, 0)
    return ans


print(gen(3))

['((()))', '(()())', '(())()', '()(())', '()()()']


In [3]:
def gen(n):
    l=[]
    def oc(s,o,c):
        if o==n and c==n:
            l.append(s)
            return 
        if o<n:
            oc(s+"(",o+1,c)
        if c<o:
            oc(s+")",o,c+1)
    oc("",0,0)
    return l
print(gen(3))

['((()))', '(()())', '(())()', '()(())', '()()()']


## 1. Write a Python Program to Convert Decimal to Binary, Octal and Hexadecimal.

In [ ]:
number=int(input('Enter the number '))
b=bin(number)
print(f'binary {b}')
o=oct(int(number))
print(f'octal {o}')
he=hex(number)
print(f'hex {he}')


## 2. Write a Python Program to Display Fibonacci Sequence Using Recursion.

In [ ]:
# using simple function recursion
def f(n):
    if n==0 or n==1:
        return n
    return f(n-1)+f(n-2)
n=int(input())
for i in range(n):
    print(f(i))

In [ ]:
## this  problem is solved using tail recursion.
## tail recursion means after the return no task is remaining.
n=int(input())
def f(n,a=0,b=1):
    if n==0: return a
    return f(n-1,b,a+b)
for i in range(n): print(f(i))


In [ ]:
# this is using lambda function and reduce the number of lines of code
f=lambda n: n if n==1 or n==0 else f(n-1)+f(n-2)
n=int(input())
for i in range(n):
    print(f(i))

In [ ]:
# using simple for-loop 
n=int(input())
a=0
b=1
print(a,b)
for i in range(n):
    c=a+b
    print(c)
    a=b
    b=c



## 3. Write a Python Program to Find Factorial of Number Using Recursion.

In [ ]:
# using simple function 
n=int(input())
def f(n):
    if n==0 or n==1:
        return n
    return n*f(n-1)
f(n)

In [ ]:
## this  problem is solved using tail recursion.
## tail recursion means after the return no task is remaining.
n=int(input())
def f(n,r=1):
    if n==1 or n==0:
        return r
    return f(n-1,r*n)
f(5)

In [ ]:
# using lambda 
n=int(input())
f=lambda x: 1 if x==1 or x==0  else x*f(x-1)
f(n)

In [ ]:
# using built-in function 
from functools import reduce
n=int(input())
print(reduce(lambda x,y:x*y,range(1,n+1),1))

## 4. Write a Python Program to calculate the natural logarithm of any number

In [ ]:
import math as m
m.log(8)

## 5. Write a Python Program to find sum of array.
In Python, an array is a data structure used to store a collection of elements, each identified
by an index or a key. Unlike some other programming languages, Python does not have a
built-in array type. Instead, the most commonly used array-like data structure is the list.

A list in Python is a dynamic array, meaning it can change in size during runtime. Elements
in a list can be of different data types, and you can perform various operations such as
adding, removing, or modifying elements. Lists are defined using square brackets [] and
can be indexed and sliced to access specific elements or sublists.

Example of a simple list in Python:
my_list = [1, 2, 3, 4, 5]

In [1]:
import numpy as np
arr=np.arange(25).reshape(5,5)
print(arr)
print(np.sum(arr))
sum(np.arange(25))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
300


300

## 6. Write a Python Program to find largest element in an array

In [ ]:
import numpy as np
arr=np.arange(25).reshape(5,5)
print(arr)
print(np.max(arr))

## 7. Write a Python Program for array rotation
Original Array: [1, 2, 3, 4, 5]

Rotated Array: [3, 4, 5, 1, 2]

In [2]:
oa=[1, 2, 3, 4, 5]
po=int(input(f'your posiion must be less than {len(oa)}'))
oa=oa[po:]+oa[:po]
oa

your posiion must be less than 5 4


[5, 1, 2, 3, 4]

## 8. Write a Python Program to Split the array and add the first part to the end?
Original Array: [1, 2, 3, 4, 5]

Array after splitting and adding: [4, 5, 1, 2, 3]

In [ ]:
oa=[1, 2, 3, 4, 5]
po=int(input(f'your posiion must be less than {len(oa)}'))
oa=oa[po:]+oa[:po]
oa

## 9. Check if a Given Array is Monotonic

A **monotonic array** is one that is entirely **non-increasing** or **non-decreasing**.

### **Example Arrays:**

```python
arr1 = [1, 2, 2, 3]  # Monotonic (non-decreasing)
arr2 = [3, 2, 1]     # Monotonic (non-increasing)
arr3 = [1, 3, 2, 4]  # Not monotonic


In [3]:
arr1 =[1, 3, 2, 4]
dl=sorted(arr1,reverse=True)
al=sorted(arr1)
if dl==arr1 or al==arr1:
    print("monotonic")
else:
    print('non monotonic')

non monotonic


In [ ]:
# arr1 = [0,1, 2, 2, 3]
# arr1.sort(reverse=False)
# arr1
# # sa=arr1.sorted()

## 10. Write a Python Program to Add Two Matrices.

In [4]:
import numpy as np
m1=np.arange(25).reshape(5,5)
m2=np.arange(25).reshape(5,5)
m1+m2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

## 11. Write a Python Program to Sort Words in Alphabetic Order.
```Input:- Enter a string: suresh ramesh vibhuti gulgule raji ram shyam ajay
Output:- The sorted words are:
Ajay
Gulgule
Raji
Ram
Ramesh
Shyam
Suresh
Vibhuti

In [ ]:
s=input().split()
s.sort()
for i in s: print(i.capitalize())    

## 12. Write a Python Program to Remove Punctuation From a String.[Do not use REGEX!]

In [5]:
l=['.', ',', '?', '!', ':', ';',  '"', '-', '—', '–', '(', ')', '[', ']', '{', '}', '/', '...', '@', '#', '$', '%', '&', '*', '+', '=', '<', '>', '_']
ss=''
for i in input(): 
    if i in l:
        pass
    else:
        ss=ss+i
ss

 pavan ....


'pavan '

## 13. Write a Python program to Multiply all numbers in the list.

In [6]:
l=[ 3,  2,  4,  6,  8] 
v=1
for i in l:v*=i
v

1152

In [9]:
count=0
for i in range(1,101):
    count+=i

count

5050

## 14. Write a Python program to find smallest number in a list.

In [10]:
# without using built-in function 
l=[ 3,  2,  4,  6,  8]
m=l[0]
for i in range(len(l)):  
    if m>l[i]:
        m=l[i] 
       
m

2

In [13]:
l=[ 3,  2,  4,  6,  8,1]
s=l[0]
for i in range(len(l)):
    if s>l[i]:
        s=l[i]

s

1

In [ ]:
l=[ 3,  2,  4,  6,  8]
print(min(l))

## 15. Write a Python program to find largest number in a list

In [14]:
l=[ 3,  2,  4,  6,  8]
m=l[0]
s=m
for i in range(len(l)): 
    if m<l[i]:
        s=m
        m=l[i] 
        
m


8

## 16. Write a Python program to find second largest number in a list.

In [15]:
l=[ 2,3,1,4,9]
m=l[0]
if len(l)<2:
    print("no second largest num")
else:
    for i in range(len(l)): 
        if m<l[i]:
            s=m
            m=l[i] 
        else:
            s=l[i]
    else:
        print(s)
        


4


In [ ]:
l=[ 2]
m=l[0]
if len(l)<2:
    print("no second largest num")
else:
    for i in range(len(l)): 
        if m<l[i]:
            s=m
            m=l[i] 
        else:
            s=l[i]
        
s

## 17. Write a Python program to find N largest elements from a list.

In [ ]:
l=[ 3,  2,  4,  6,  8]


## 18. Write a Python program to print even numbers in a list.

In [ ]:
l=[ 3,  2,  4,  6,  8]
r=filter(lambda x: x%2==0,l)
list(r)

## 19. Write a Python program to 1print odd numbers in a List

In [ ]:
l=[ 3,  2,  4,  6,  8]
o=filter(lambda x: x%2!=0,l)
list(o)

## 20. Write a Python program to Remove empty List from List.


In [ ]:
l=[ 3,  2,  4,  6,  8,[]]
ll=list(filter(None,l))
ll

In [ ]:
l=[ 3,  2,  4,  6,  8,[]]
R=[i for i in l if i!=[]]
R

In [ ]:
l=[ 3,  2,  4,  6,  8,[]]
ll=[]
for i in range(len(l)):
    if type(l[i])==list and len(l[i])==0: l.remove(l[i])
l

## 21. Write a Python program to Count occurrences of an element in a list

In [ ]:
l=[ 3,  2,  4,  6,  8,[]]
ll=[]
for i in l: ll.append(l.count(i))
ll

In [ ]:
l = [3, 2, 4, 6, 8]
d={}
for i in l:
    if i in d:
        d[i]+=1
    else:
        d[i]=1
d

In [ ]:
from collections import Counter
l = [3, 2, 4, 6, 8]
print(Counter(l))

## 22. Write a Python program to find words which are greater than given length k.

## 23. Write a Python program to split and join a string.

In [ ]:
s=input()
s=s.split()
print(s)
' '.join(s)

## 24. Write a Python program to find uncommon words from two Strings.

In [ ]:
set(input('enter first string').lower().split()).symmetric_difference(set(input('enter second string').lower().split()))

In [ ]:
s=input().lower()
ss=input().lower()
for i in s:
    if i not in set(ss) and i not in '  ':
        print(i)
for i in ss:
    if i not in set(s) and i not in '  ':
        print(i)    

## 25. Write a Python program to find all duplicate characters in string.

In [ ]:
# import time 
s=input().lower()
# print(time.ctime())
print([i for i in set(s) if s.count(i)>1 and i not in ' '])
# print(time.ctime())

In [ ]:
import time 
s=input().lower()
print(time.ctime())
for i in set(s):
    if s.count(i)>1 and i not in ' ':
        print(i)
print(time.ctime())

## 26. Write a Python program to Extract Unique dictionary values.
```
Input: - my_dict = {'a': 10, 'b': 20, 'c': 10, 'd': 30, 'e': 20}
output: - [10, 20, 30]

#### actually this method is convert the give input into real python literals 

In [ ]:
# how can i take a dictionary as input exactlly
import ast 
i=input()
d=ast.literal_eval(i)  # actually this method is convert the give input into real python literals 
type(d)

In [ ]:
my_dict = {'a': 10, 'b': 20, 'c': 10, 'd': 30, 'e': 20}
set(my_dict.values())

In [ ]:
my_dict = {'a': 10, 'b': 20, 'c': 10, 'd': 30, 'e': 20}
l=[]
for i in my_dict:
    if my_dict[i] not in l:
        l.append(my_dict[i])
l

## 27. Write a Python program to find the sum of all items in a dictionary.
```
Input: - my_dict = {'a': 10, 'b': 20, 'c': 10, 'd': 30, 'e': 20}
Output: - Sum of all items in the dictionary: 150


In [ ]:
my_dict = {'a': 10, 'b': 20, 'c': 10, 'd': 30, 'e': 20}
sum(my_dict.values())

## 28. Write a Python program to Merging two Dictionaries

In [ ]:
my_dict = {'a': 10, 'b': 20, 'c': 10, 'd': 30, 'e': 20}
my_dicts = {'a': 0, 'bb': 20, 'cc': 10, 'dd': 30, 'ee': 20}
{**my_dict,**my_dicts}

In [ ]:
my_dict = {'a': 10, 'b': 20, 'c': 10, 'd': 30, 'e': 20}
my_dicts = {'a': 0, 'bb': 20, 'cc': 10, 'dd': 30, 'ee': 20}
my_dict | my_dicts

In [ ]:
my_dict = {'a': 10, 'b': 20, 'c': 10, 'd': 30, 'e': 20}
my_dicts = {'a': 0, 'bb': 20, 'cc': 10, 'dd': 30, 'ee': 20}
my_dict.update(my_dicts)
my_dict

## 29. Write a Python program to convert key-values list to flat dictionary.
```
key_values_list = [('a', 1), ('b', 2), ('c', 3), ('d', 4)]

In [ ]:
key_values_list = [('a', 1), ('b', 2), ('c', 3), ('d', 4)]
dict(key_values_list)

In [ ]:
key_values_list = [('a', 1), ('b', 2), ('c', 3), ('d', 4)]
d={}
for i  in key_values_list:
    d[i[0]]=i[1]
d

## 30.  Define a class with a generator which can iterate the numbers, which are divisible by 7, between a given range 0 and n.

In [7]:
class generator:
    def __init__(s,rs,re):
        s.rs=rs
        s.re=re
    def m(s):
        for i in range(s.rs,s.re):
            if i%7==0:
                yield i

o=generator(0,100)
for i in o.m():
    print(i)

0
7
14
21
28
35
42
49
56
63
70
77
84
91
98


## 31. Write a program to compute the frequency of the words from the input. The output should output after sorting the key alphanumerically. Suppose the following input is supplied to the program:
```
"New to Python or choosing between Python 2 and Python 3? Read Python 2 or Python 3."
Then, the output should be:
2:2
3.:1
3?:1
New:1
Python:5
Read:1
and:1
between:1
choosing:1
or:2
to:1

In [ ]:
words = input().split()

freq = {}

for w in words:
    freq[w] = freq.get(w, 0) + 1
    
# sort keys alphanumerically and print
for k in sorted(freq):               ### here na python sorted method sorts the strings based on the ascii values 
    print(f"{k}:{freq[k]}")


## 32. Define a class Person and its two child classes: Male and Female. All classes have a method "getGender" which can print "Male" for Male class and "Female" for Female class.

In [ ]:
# using abstract method.

from abc import ABC, abstractmethod

class person(ABC):
    def __init__(s):
        pass

    @abstractmethod
    def getgender(s):
        pass

class male(person):
    def __init__(s):
        pass 
    def getgender(s):
        print('male')

class female(person):
    def __init__(s):
        pass
    def getgender(s):
        print("female")
om=male()
of=female()
om.getgender()
of.getgender()


## 33. Please write a program to generate all sentences where subject is in ["I", "You"] and verb is in ["Play", "Love"] and the object is in ["Hockey","Football"].

In [ ]:
# USING itertools
from itertools import product 
s= ["I", "You"]
v=["Play", "Love"] 
o=["Hockey","Football"]
for i,j,k in product(s,v,o): print(f"{i} {j} {k}")

In [ ]:
# using simple for-loop 
s= ["I", "You"]
v=["Play", "Love"] 
o=["Hockey","Football"]
for i in s:
    for j in v:
        for k in o:
            print(f'{i} {j} {k}')

## 34. Please write a program using generator to print the even numbers between 0 and n in comma separated form while n is input by console.
```
Example:
If the following n is given as input to the program:
10
Then, the output of the program should be:
0,2,4,6,8,10


In [ ]:
def g(n):
    for i in range(0, n + 1):
        if i % 2 == 0:
            yield i

n = int(input())
print(",".join(str(i) for i in g(n)))

## 35. Define a class named Shape and its subclass Square. The Square class has an init function which takes a length as argument. Both classes have an area function which can print the area of the shape where Shape's area is 0 by default.

In [ ]:
class shape:
    def area(s):
        print(0)

class square(shape):
    def __init__(s,l):
        s.l=l
    def area(s):
        print(s.l*s.l)
o=square(22)
o.area()


## 36. Create a function that takes an angle in radians and returns the corresponding angle in degrees rounded to one decimal place.
```
Examples
radians_to_degrees(1) ➞ 57.3
radians_to_degrees(20) ➞ 1145.9
radians_to_degrees(50) ➞ 2864.8

In [ ]:
def f(r): return round(r*180/3.14,1)
f(20)

## 37. Write a function that stutters a word as if someone is struggling to read it. The first two letters are repeated twice with an ellipsis ... and space after each, and then the word is pronounced with a question mark ?.
```
Examples
stutter("incredible") ➞ "in... in... incredible?"
stutter("enthusiastic") ➞ "en... en... enthusiastic?"
stutter("outstanding") ➞ "ou... ou... outstanding?"
Hint :- Assume all input is in lower case and at least two characters long.

In [ ]:
def stutters(s): return f'{s[:2]}... {s[:2]}... {s}?'
stutters(input().lower())

## 38. Given the side length x find the area of a hexagon.
```
Examples
area_of_hexagon(1) ➞ 2.6
area_of_hexagon(2) ➞ 10.4
area_of_hexagon(3) ➞ 23.4

In [ ]:
import math
x=float(input())
round(((3*math.sqrt(3))/2)*(x**2),1)

## 39. Create a function that takes three arguments a, b, c and returns the sum of the numbers that are evenly divided by c from the range a, b inclusive.
```
Examples
evenly_divisible(1, 10, 20) ➞ 0
# No number between 1 and 10 can be evenly divided by 20.
evenly_divisible(1, 10, 2) ➞ 30
# 2 + 4 + 6 + 8 + 10 = 30
evenly_divisible(1, 10, 3) ➞ 18
# 3 + 6 + 9 = 18

In [ ]:
def f(a,b,c):
    s=0
    for i in range(a,b+1):
        if i%c==0:
            s+=i
    return s
f(1, 10, 20)

## 40. Create a function that returns True if a given inequality expression is correct and False otherwise
```
Examples
correct_signs("3 < 7 < 11") ➞ True
correct_signs("13 > 44 > 33 <1") ➞ False
correct_signs("1 < 2 < 6 < 9 > 3") ➞ True

In [ ]:
def f(e):
    return eval(e)
print(f(input()))

## 41. Create a function that replaces all the vowels in a string with a specified character.
```Examples
replace_vowels("the aardvark", "#") ➞ "th# ##rdv#rk"
replace_vowels("minnie mouse", "?") ➞ "m?nn?? m??s?"
replace_vowels("shakespeare", "*") ➞ "shkspr*"

In [ ]:
def f():
    s=input()
    sps=input()
    ss=''
    for i in s:
        if i.lower() in 'aeiou':
            ss+=sps
        else:
            ss+=i
    return ss
f()

## 42. Write a function that calculates the factorial of a number recursively.
```
Examples
factorial(5) ➞ 120
factorial(3) ➞ 6
factorial(1) ➞ 1
factorial(0) ➞ 1

In [ ]:
def f(n,r=1):
    if n==1 or n==0:
        return r
    else:
        return f(n-1,r*n)
f(int(input()))

In [ ]:
# simple recursion 
def f(n):
    if n==1 or n==0:
        return n
    else:
        return n*f(n-1)

f(int(input()))

In [ ]:
f=lambda x: x if x==1 or x==0 else x*f(x-1)
f(5)

## 43. Create a function that takes a list of non-negative integers and strings and return a new list without the strings.
```
Examples
filter_list([1, 2, "a", "b"]) ➞ [1, 2]
filter_list([1, "a", "b", 0, 15]) ➞ [1, 0, 15]
filter_list([1, 2, "aasf", "1", "123", 123]) ➞ [1, 2, 123]

In [ ]:
def f(l):
    return [i for i in l if isinstance(i,int)]


In [ ]:
import ast
i=input()
l=ast.literal_eval(i)
def f(l):
    ll=[]
    for i in l:
        if str(i).isdigit() and i>=0:
            ll.append(i)
    return ll
f(l)

## 44. The "Reverser" takes a string as input and returns that string in reverse order, with the opposite case.
```
Examples
reverse("Hello World") ➞ "DLROw OLLEh"
reverse("ReVeRsE") ➞ "eSrEvEr"
reverse("Radar") ➞ "RADAr"

In [ ]:
ss=input()
def f(ss):
    return s.swapcase()[::-1]
f(ss)

## 45. Create a function that takes a string and returns a string in which each character is repeated once.
```
Examples
double_char("String") ➞ "SSttrriinngg"
double_char("Hello World!") ➞ "HHeelllloo WWoorrlldd!!"
double char("1234! ") ➞ "11223344!! "

In [ ]:
def f(s):
    return ''.join(i+i for i in s)
f(input())

In [ ]:
def f(s):
    ns=''
    for i in s:
        ns=ns+(i*2)
    return ns
f('amol')

## 46. Using list comprehensions, create a function that finds all even numbers from 1 to the given number.
```
Examples
find_even_nums(8) ➞ [2, 4, 6, 8]
find_even_nums(4) ➞ [2, 4]
find_even_nums(2) ➞ [2]

In [ ]:
[i for i in range(2,int(input())+1,2)]

## 47. Create a function that takes a list of strings and integers, and filters out the list so that it returns a list of integers only.
```
Examples
filter_list([1, 2, 3, "a", "b", 4]) ➞ [1, 2, 3, 4]
filter_list(["A", 0, "Edabit", 1729, "Python", 1729]) ➞ [0, 1729]
filter_list(["Nothing", "here"]) ➞ []

In [ ]:
def f(l):
    return [i for i in l if isinstance(i,int)]
f([1,2,3,4,5,6,7,8,9,0,'a','a'])

## 48. Hamming distance is the number of characters that differ between two strings.
```
To illustrate:
String1: "abcbba"
String2: "abcbda"
Hamming Distance: 1 - "b" vs. "d" is the only difference.
```

#### Create a function that computes the hamming distance between two strings.
```
Examples
hamming_distance("abcde", "bcdef") ➞ 5
hamming_distance("abcde", "abcde") ➞ 0
hamming_distance("strong", "strung") ➞ 1

In [ ]:
s1=input()
s2=input()
sum( i!=j for i,j in zip(s1,s2))

In [ ]:
s1=input()
s2=input()
c=0
for i  in range(len(s1)):
    if s1[i]!=s2[i]:
        c+=1
c

## 49. Write a function that moves all elements of one type to the end of the list.
```
Examples
move_to_end([1, 3, 2, 4, 4, 1], 1) ➞ [3, 2, 4, 4, 1, 1]
Move all the 1s to the end of the array.
move_to_end([7, 8, 9, 1, 2, 3, 4], 9) ➞ [7, 8, 1, 2, 3, 4, 9]
move_to_end(["a", "a", "a", "b"], "a") ➞ ["b", "a", "a", "a"]


In [ ]:
def move_to_end(lst, e):
    return [x for x in lst if x != e] + [x for x in lst if x == e]


In [ ]:
l=[1,2,3,4,4,4,5,6,7]
def F(l,e):
    for i in range(l.count(e)):
        l.remove(e)
        l.append(e)
    return l
F(l,4)

## 50. Create a function that takes a single string as argument and returns an ordered list containing the indices of all capital letters in the string.
```
Examples
index_of_caps("eDaBiT") ➞ [1, 3, 5]
index_of_caps("eQuINoX") ➞ [1, 3, 4, 6]
index_of_caps("determine") ➞ []
index_of_caps("STRIKE") ➞ [0, 1, 2, 3, 4, 5]
index_of_caps("sUn") ➞ [1]


In [ ]:
def f(s):
    return [ i for i in s if i.isupper() ]
f('amol')

## 51. Create a function that takes a list of numbers between 1 and 10 (excluding one number) and returns the missing number.
```
Examples
missing_num([1, 2, 3, 4, 6, 7, 8, 9, 10]) ➞ 5
missing_num([7, 2, 3, 6, 5, 9, 1, 4, 8]) ➞ 10
missing_num([10, 5, 1, 2, 4, 6, 8, 3, 9]) ➞ 7


In [ ]:
def f(l):
    return [i for i in range(1,11) if i not in l]
    
f([1, 2, 3, 4, 6, 7, 8, 9, 10])

## 52. An isogram is a word that has no duplicate letters. Create a function that takes a string and returns either True or False depending on whether or not it's an "isogram".
```
Examples
is_isogram("Algorism") ➞ True
is_isogram("PasSword") ➞ False
- Not case sensitive.
is_isogram("Consecutive") ➞ False
```
### Note-
Ignore letter case (should not be case sensitive).
All test cases contain valid one word strings

In [ ]:
def f(s):
    return len(s)==len(set(s))
f("Algorism")

## 53. Create a function that takes a string and returns True or False, depending on whether the characters are in order or not.
```
Examples
is_in_order("abc") ➞ True
is_in_order("edabit") ➞ False
is_in_order("123") ➞ True
is_in_order("xyzz") ➞ True
```
**Notes**
You don't have to handle empty strings.

In [ ]:
def f(s):
    return ''.join(sorted(s,key=str.lower))==s
f("edabit")

## 54. Create a function that takes a number as an argument and returns True or False depending on whether the number is symmetrical or not. A number is symmetrical when it is the same as its reverse.
```
Examples
is_symmetrical(7227) ➞ True
is_symmetrical(12567) ➞ False
is_symmetrical(44444444) ➞ True
is_symmetrical(9939) ➞ False
is_symmetrical(1112111) ➞ True

In [ ]:
def f(s):
    return s==s[::-1]
f('7227')

## 55. Given a string of numbers separated by a comma and space, return the product of the numbers.
```
Examples
multiply_nums("2, 3") ➞ 6
multiply_nums("1, 2, 3, 4") ➞ 24
multiply_nums("54, 75, 453, 0") ➞ 0
multiply_nums("10, -2") ➞ -20

In [ ]:
from functools import reduce
def f(l):
   
    return reduce(lambda x,y: int(x)*int(y), l.split(', '))
f("54, 75, 453, 0")

In [ ]:
def f(l):
    s=1 
    for i in l.split(', '):
        s=s*int(i
    return s
f("54, 75, 453, 0")

## 56. Create a function that sorts a list and removes all duplicate items from it.
```
Examples
setify([1, 3, 3, 5, 5]) ➞ [1, 3, 5]
setify([4, 4, 4, 4]) ➞ [4]
setify([5, 7, 8, 9, 10, 15]) ➞ [5, 7, 8, 9, 10, 15]
setify([3, 3, 3, 2, 1]) ➞ [1, 2, 3]

In [ ]:
[6]+[2]

In [ ]:
def f(l):
    ll=[l[-1]]
    return [  l[i]   for i in range(len(l)-1)  if l[i]!=l[i+1]] + ll
f([1, 3, 3, 5, 5])

## 57. Create a function that returns the mean of all digits.
```
Examples
mean(42) ➞ 3
mean(12345) ➞ 3
mean(666) ➞ 6
 ```
**Notes**
- The mean of all digits is the sum of digits / how many digits there are (e.g. mean of digits in 512 is (5+1+2)/3(number of digits) = 8/3=2).
- The mean will always be an integer.

In [ ]:
def f(l):
    return sum([int(i) for i in l])/len(l)
f(input())

In [ ]:
def f():
    n=int(input())
    s=0
    c=0
    while n>0:
        rem=n%10
        s=s+rem
        n=n//10
        c+=1
    return s/c
f()

## 58. Create a function that takes a list of strings and return a list, sorted from shortest to longest.
```
Examples
sort_by_length(["Google", "Apple", "Microsoft"]) ➞ ["Apple", "Google", "Microsoft"]
sort_by_length(["Leonardo", "Michelangelo", "Raphael", "Donatello"]) ➞ ["Raphael",
"Leonardo", "Donatello", "Michelangelo"]
sort_by_length(["Turing", "Einstein", "Jung"]) ➞ ["Jung", "Turing", "Einstein"]
```
**Notes**
- All test cases contain lists with strings of different lengths, so you won't have to deal

In [ ]:
def f(l):
    return sorted(l,key=len)
f(["Turing", "Einstein", "Jung"])

In [ ]:
l=["Turing", "Einstein", "Jung"]
def f(l):
    d={}
    for i in l:
        d[len(i)]=i
    l=sorted(d)
    ll=[]
    for i in l:
        ll.append(d[i])
    return ll
f(l)

## 59. Write a function that creates a dictionary with each (key, value) pair being the (lower case, upper case) versions of a letter, respectively.
```
Examples
mapping(["p", "s"]) ➞ {"p": "P", "s": "S"}
mapping(["a", "b", "c"]) ➞ { "a": "A", "b": "B", "c": "C" }
mapping(["a", "v", "y", "z"]) ➞ { "a": "A", "v": "V", "y": "Y", "z": "Z" }
```
**Notes**
- All of the letters in the input list will always be lowercase.

In [ ]:
def f(l):
    return {i:i.upper() for i in l}
f(["a", "b", "c"])

## 60. Create a function that takes a string as input and capitalizes a letter if its ASCII code is even and returns its lower case version if its ASCII code is odd.
```
Examples
ascii_capitalize("to be or not to be!") ➞ "To Be oR NoT To Be!"
ascii_capitalize("THE LITTLE MERMAID") ➞ "THe LiTTLe meRmaiD"
ascii_capitalize("Oh what a beautiful morning.") ➞ "oH wHaT a BeauTiFuL
moRNiNg. "

In [ ]:
def f(s):
    return ''.join(i.upper() if ord(i)%2==0 else i.lower() for i in s)
f("to be or not to be!")

In [ ]:
def f(s):
    ns=''
    for i in s:
        if ord(i)%2==0:
            ns=ns+i.upper()
        else:
            ns=ns+i.lower()
    return ns
f("to be or not to be!")

## 61. Generate a random date between given start and end dates

In [ ]:
from datetime import datetime, timedelta
import random
s_d=datetime(2023,1,1)
e_d=datetime(2024,12,31)
r_d=s_d+timedelta(days=random.randint(0,(e_d-s_d).days))
print(r_d.date())

## 62. Roll dice in such a way that every time you get the same number Dice has 6 numbers (from 1 to 6). Roll dice in such a way that every time you must get the same output number. do this 5 times.

In [ ]:
import random 
r=random.randint(1,6)
for _ in range(5):
    print(r)

## 63. Random Lottery Pick. Generate 100 random lottery tickets and pick two lucky tickets from it as a winner.
**Note you must adhere to the following conditions:**
- The lottery number must be 10 digits long.
- All 100 ticket number must be unique

In [ ]:
import random 
t=set()
while len(t) <100:
    tis=random.randint(1000000000, 9999999999)
    t.add(tis)
t=list(t)
wn=random.sample(t,2)
# print(t)
print(wn)

## 64. Calculate number of days between two given dates
- Given:
  
(2020-02-25)date_1 = datetime(2020, 2, 25)

(2020-09-17)date_2 = datetime(2020, 9, 17)
- Expected output:
205 days


In [ ]:
from datetime import datetime
sd=datetime(2020,2,24)
ed=datetime(2020,2,29)
d=(ed-sd).days
d

## 65. Convert the following datetime into a string
- Given:

given_date = datetime(2020, 2, 25)
- Expected output:

"2020-02-25 00:00:00"

In [ ]:
from datetime import datetime
given_date = datetime(2020, 2, 25)
dstring=given_date.strftime("%y-%m-%d")
dstring

## 66. Print current time in milliseconds

In [ ]:
import time 
int(time.time()*1000)

## 67. Find the day of the week of a given date
```
Given:
given_date = datetime(2020, 7, 26)
Expected output:
Sunday


In [ ]:
from datetime import datetime
gd=datetime(2020, 7, 26)
dn=gd.strftime("%A")
dn

## 68. Convert string into a datetime object
```
For example, You received the following date in string format. Please convert it into Python’s DateTime
object
date_string = "Feb 25 2020 4:20PM"

In [ ]:
date_string = "Feb 25 2020 4:20PM"
import time
dt=datetime.strptime(date_string,"%b %d %Y %I:%M%p")
dt

## 69. Write a Python program that:
- Counts the total number of opening ( and closing ) parentheses in the string.
- Tracks the position of each opening(and each closing) in the string, and outputs their respective positions.
- You cannot use built - in functions like count(), find(), etc.to solve this problem.
- input_text = '(((>0)())(('
- The program should print:
The total count of opening parentheses ( and closing parentheses ).
The 1-based index positions of each opening parenthesis ( and each closing parenthesis ).

In [ ]:
s='(((>0)())(('
op,cp=0,0
opl,cpl=[],[]
for i in range(len(s)):
    if s[i]=='(':
        op+=1
        opl.append(i+1)
    if s[i]==')':
        cp+=1
        cpl.append(i+1)
print(f"opening para ={op}, closing para={cp}, oening para lst ={opl}, closing para lst={cpl}")

D 100
W 200

- D means deposit while W means withdrawal.
- Suppose the following input is supplied to the program:
```
D 300
D 300
W 200
D 100
```
- Then, the output should be:
500

**Hints:**
- In case of input data being supplied to the question, it should be assumed to be a console input.


In [ ]:
c=0
b=0
while c==0:
    i=input('''
    enter 1 for deposit amount
    enter 2 for withdraw amount
    enter 3 for showing blance
    enter 4 for breaking this loop
    ''')
    if i=='1':
        d=int(input('enter deposit amount'))
        b+=d
    elif i=='2':
        w=int(input('enter withdraw amount'))
        b-=w
    elif i=='3':
        print("balance = ",b)
    elif i=='4':
        break

## 71. You are required to write a program to sort the (name, age, height) tuples by ascending order where name is string, age and height are numbers. The tuples are input by console. The sort criteria is:
- 1: Sort based on name;
- 2: Then sort based on age;
- 3: Then sort by score.
The priority is that name > age > score.

If the following tuples are given as input to the program:
- Tom,19,80
- John,20,90
- Jony,17,91
- Jony,17,93
- Json,21,85

Then, the output of the program should be:
[('John', '20', '90'), ('Jony', '17', '91'), ('Jony', '17', '93'), ('Json', '21', '85'), ('Tom', '19', '80')]
```
Hints:
In case of input data being supplied to the question, it should be assumed to be a console input.
use itemgetter to enable multiple.

In [1]:
l=[]
while True:
    data=input()
    if not data:
        break
    name,age,height=data.split(',')
    l.append((name,int(age),float(height)))
sorted(l,key=lambda x: (x[0],x[1],x[2]))

[]

## 72. Write a program which can map() and filter() to make a list whose elements are square of even number in [1,2,3,4,5,6,7,8,9,10].

**Hints:**

- Use map() to generate a list.
- Use filter() to filter elements of a list.
- Use lambda to define anonymous functions.

In [ ]:
l=[1,2,3,4,5,6,7,8,9,10]
el=list(filter(lambda x: x%2==0,l))
sl=list(map(lambda x: x*x,el))
sl

## 73. Assuming that we have some email addresses in the "username@companyname.com" format, please write program to print the user name of a given email address. Both user names and company names are composed of letters only.

```Example:
If the following email address is given as input to the program:
john@google.com
Then, the output of the program should be:
john
```
- In case of input data being supplied to the question, it should be assumed to be a console input.

**Hints:** Use \w to match letters.

In [ ]:
import re
e=input()
u=re.match(r"(\w+)@", e)
u.group(1)

In [ ]:
e=input()
e.split("@")[0]

In [ ]:
i=input()
for s in i:
    if s!='@':
        print(s,end='')
    else:
        break
        

## 74. Write a program to solve a classic ancient Chinese puzzle: We count 35 heads and 94 legs among the chickens and rabbits in a farm. How many rabbits and how many chickens do we have?

**Hint:**
- Use for loop to iterate all possible solutions.

In [2]:
for c in range(1,36):
    for r in range(1,36):
        if ((c*2)+(r*4))==94 and c+r==35:
            print(c,r)
            break
    

23 12


## 75. Write a program which accepts a sequence of comma separated 4 digit binary numbers as its input and then check whether they are divisible by 5 or not. The numbers that are divisible by 5 are to be printed in a comma separated sequence.
```
Example:
0100,0011,1010,1001
Then the output should be:
1010
```
**Notes:** Assume the data is input by console.

**Hints:**
- In case of input data being supplied to the question, it should be assumed to be a console input.


In [ ]:
b=input().split(',')
for i in b:
    n=0
    ln=len(i)-1
    for j in i:
        n=(int(j)*(2**ln))+n
        ln=ln-1
    if n%5==0:
        print(i)
        

In [ ]:
i=input().split(',')
[ b for b in i if int(b,)%5==0]

## 76. Write a function to find the longest common prefix string amongst an array of strings.If there is no common prefix, return an empty string.
```
Example 1:
Input: ["flower","flow","flight"]
Output: "fl"

Example 2:
Input: ["dog","racecar","car"]

Output:
Explanation: There is no common prefix among the input strings.
```
**Note:**- All given inputs are in lowercase letters a-z.

In [ ]:
l=sorted(["flower","flow","flight"])
for i in range(len(l[0])):
    if l[0][i]==l[1][i]:
        print(l[0][i],end='')
    else:
        break

## 77. Given n pairs of parentheses, write a function to generate all combinations of well-formed parentheses.
```
For example, given n = 3, a solution set is:
[
  "((()))",
  "(()())",
  "(())()",
  "()(())",
  "()()()"
	]

In [ ]:
def gen(n):
    ans = []

    def f(s, o, c):
        if o == n and c == n:
            ans.append(s)
            return

        if o < n:
            f(s + "(", o + 1, c)

        if c < o:
            f(s + ")", o, c + 1)

    f("", 0, 0)
    return ans


print(gen(3))


## My question backtracking 
# Given a string of digits, generate all possible combinations of letters based on the phone keypad mapping.

In [ ]:
def lc(d):
    if not d:
        return []
    keypad = {
        "2": "abc",
        "3": "def",
        "4": "ghi",
        "5": "jkl",
        "6": "mno",
        "7": "pqrs",
        "8": "tuv",
        "9": "wxyz"
    } 

    res=[]

    def bc(i,mc):
        if i==len(d):
            res.append(mc)
            return 
        let=keypad[d[i]]
        for ch in let:
            bc(i+1,mc+ch)
    bc(0,'')
    return res
print(lc('23'))

## 78. Write a program that calculates and prints the value according to the given formula:
```
Q= Squareroot of 2CD/H
Following are the fixed values of C and H:
C is 50. H is 30.
D is the variable whose values should be input to your program in a commaseparated sequence.
```
**Example**
```
Let us assume the following comma separated input sequence is given to the
program:
100,150,180
The output of the program should be:
18,22,24
```

In [8]:
import math
c=50
h=30
d=input().split(',')
for i in d:
    print(int(math.sqrt((c*int(i))/30)))


 100,150,180


12
15
17


## 79. Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. The element value in the i-th row and j-th column of the array should be i*j.
- Note: i=0,1.., X-1; j=0,1,¡Y-1.
- Example
- Suppose the following inputs are given to the program: 3,5
- Then, the output of the program should be: [[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [42]:
# this code shows my lazyness with conceptual logic in pyhon.
x,y=map(int,input().split(","));m=list(map(lambda i:list(map(lambda j:i*j ,range(y)))   ,range(x)));m

 3,5


[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

In [22]:
l=[]
for i in range(3):
    ll=[]
    for j in range(5):
        ll.append(i*j)
    l.append(ll)
l

[[0, 0, 0, 0, 0], [0, 1, 2, 3, 4], [0, 2, 4, 6, 8]]

## 80. Write a program that accepts a sentence and calculate the number of letters and digits. Suppose the following input is supplied to the program:
- hello world! 123
- Then, the output should be:

LETTERS 10

DIGITS 3

In [70]:
s=input()
print(sum((i.isalpha() for i in s)))
print(sum((i.isdigit()for i in s)))

 fghjk22


5
2


In [69]:
s=input()
l=len(list(filter(str.isalpha,s)))
d=len(list(filter(str.isdigit,s)))
d,l

 asdv85


(2, 4)

In [56]:
s=input();l,d=0,0
for i in s:
    if i.isalpha():
        l+=1
    if i.isdigit():
        d+=1
print(f'letters = {l} \ndigit = {d}')


 asdfggh55555


letters = 7 
digit = 5


## 81. Create a function that returns the thickness (in meters) of a piece of paper after folding it n number of times. The paper starts off with a thickness of 0.5mm.
```
Examples
num_layers(1) ➞ "0.001m"
- Paper folded once is 1mm (equal to 0.001m)
num_layers(4) ➞ "0.008m"
- Paper folded 4 times is 8mm (equal to 0.008m)
num_layers(21) ➞ "1048.576m"
- Paper folded 21 times is 1048576mm (equal to 1048.576m)

In [2]:
def f(n):
    return 0.5*(2**n)/1000
f(1)

0.001

## 82. Create the function that takes a list of dictionaries and returns the sum of people's budgets.
```
Examples
get_budgets([
{ 'name': 'John', 'age': 21, 'budget': 23000 },
{ 'name': 'Steve', 'age': 32, 'budget': 40000 },
{ 'name': 'Martin', 'age': 16, 'budget': 2700 }
]) ➞ 65700
get_budgets([
{ 'name': 'John', 'age': 21, 'budget': 29000 },
{ 'name': 'Steve', 'age': 32, 'budget': 32000 },
{ 'name': 'Martin', 'age': 16, 'budget': 1600 }
]) ➞ 62600

In [80]:
l=[{ 'name': 'John', 'age': 21, 'budget': 23000 },
{ 'name': 'Steve', 'age': 32, 'budget': 40000 },
{ 'name': 'Martin', 'age': 16, 'budget': 2700 }]
s=0
for i in l: s=i['budget']+s
s

65700

## 83. Suppose that you invest $10,000 for 10 years at an interest rate of 6% compounded monthly. What will be the value of your investment at the end of the 10 year period?
- Create a function that accepts the principal p, the term in years t, the interest rate r, and the number of compounding periods per year n. The function returns the value at the end of term rounded to the nearest cent.
```
For the example:
compound_interest(10000, 10, 0.06, 12) ➞ 18193.97
Note that the interest rate is given as a decimal and n=12 because with monthly
compounding there are 12 periods per year. Compounding can also be done
annually, quarterly, weekly, or daily.
Examples
compound_interest(100, 1, 0.05, 1) ➞ 105.0
compound_interest(3500, 15, 0.1, 4) ➞ 15399.26
compound_interest(100000, 20, 0.15, 365) ➞ 2007316.26

In [94]:
def f(p,r,n,t):
    return p*(1+r/n)**(n*t)
f(p=int(input('principle ')),r=float(input('mon rate ')),n=int(input("times")),t=int(input('times in year')))

principle  10000
mon rate  0.06
times 12
times in year 10


18193.9673403229

## 84. Create a function that takes an integer and returns a list from 1 to the given number, where:
1. If the number can be divided evenly by 4, amplify it by 10 (i.e. return 10 times the
number).
2. If the number cannot be divided evenly by 4, simply return the number.
```
Examples
amplify(4) ➞ [1, 2, 3, 40]
amplify(3) ➞ [1, 2, 3]
amplify(25) ➞ [1, 2, 3, 40, 5, 6, 7, 80, 9, 10, 11, 120, 13, 14, 15, 160, 17, 18, 19, 200, 21,
22, 23, 240, 25]
```
**Notes**
- The given integer will always be equal to or greater than 1.Include the number (see example above).
- To perform this problem with its intended purpose, try doing it with list comprehensions. If that's too difficult, just solve the challenge any way you can.

In [96]:
n=int(input("enter the number "))
def f(n):
    l=[]
    for i in range(1,n+1):
        if i%4==0:
            l.append(i*10)
        elif 1:
            l.append(i)
    return l
f(n)

enter the number  4


[1, 2, 3, 40]

## 85. Write a Python Program to Make a Simple Calculator with 4 basic mathematical operations.


In [ ]:
while True:
    i=input(''' 1 enter addition
    2 enter sub
    3 enter mul
    4 entr div
    5 enter exi
    ''')
    

## 86. Create a function that takes a list of numbers and return the number that's unique.
```
Examples
unique([3, 3, 3, 7, 3, 3]) ➞ 7
unique([0, 0, 0.77, 0, 0]) ➞ 0.77
unique([0, 1, 1, 1, 1, 1, 1, 1]) ➞ 0
```
**Notes**- Test cases will always have exactly one unique number while all others are the same.

In [97]:
def f(l):
    ll=[]
    for i in l:
        if l.count(i)==1:
            print(i,end='')
f([3, 3, 3, 7, 3, 3])

7

## 87. Your task is to create a Circle constructor that creates a circle with a radius provided by an argument. The circles constructed must have two getters getArea() (PIr^2) and getPerimeter() (2PI*r) which give both respective areas and perimeter (circumference).
### For help with this class, I have provided you with a Rectangle constructor which you can use as a base example.
```
Examples
circy = Circle(11)
circy.getArea()
Should return 380.132711084365
circy = Circle(4.44)
circy.getPerimeter()
Should return 27.897342763877365
```
**Notes**- Round results up to the nearest integer.

In [106]:
class Circle:
    def __init__(s,r):
        s.r=r
    def getArea(s):
        return 3.14*(r**2)
    def getpara(s):
        return 2*3.14*r
o=Circle(11)
print(o.getArea())
oo=Circle(4.44)
oo.getpara()

3846.5


219.8

# 88. Create a function that validates whether three given integers form a Pythagorean triplet. The sum of the squares of the two smallest integers must equal the square of the largest number to be validated.
```
Examples
is_triplet(3, 4, 5) ➞ True
3² + 4² = 25
5² = 25
is_triplet(13, 5, 12) ➞ True
5² + 12² = 169
13² = 169
is_triplet(1, 2, 3) ➞ False
1² + 2² = 5
3² = 9
```
**Notes** - Numbers may not be given in a sorted order

## 89. Write a function that converts a dictionary into a list of keys-values tuples.
```
Examples
dict_to_list({
"D": 1,
"B": 2
"C": 3
}) ➞ [("B", 2), ("C", 3), ("D", 1)]
dict_to_list({
"likes": 2,
"dislikes": 3,
"followers": 10
}) ➞ [("dislikes", 3), ("followers", 10), ("likes", 2)]
```
**Notes**- Return the elements in the list in alphabetical order.

In [6]:
d={
"likes": 2,
"dislikes": 3,
"followers": 10
}
sorted(d.items())

[('dislikes', 3), ('followers', 10), ('likes', 2)]

In [4]:
d={
"likes": 2,
"dislikes": 3,
"followers": 10
}
def f(d):
    l=[]
    for k,v in d.items():
        l.append((k,v))
    return sorted(l,key=lambda x: x[0])
f(d)

[('dislikes', 3), ('followers', 10), ('likes', 2)]

## 90. Write a function, that replaces all vowels in a string with a specified vowel.
```
Examples
vow_replace("apples and bananas", "u") ➞ "upplus und bununus"
vow_replace("cheese casserole", "o") ➞ "chooso cossorolo"
vow_replace("stuffed jalapeno poppers", "e") ➞ "steffed jelepene peppers"
    
```
**Notes**- All words will be lowercase. Y is not considered a vowel.



In [1]:
def f(s,v):
    ss=''
    for i in s:
        if i in 'aeiou':
            ss=ss+v
        else:
            ss=ss+i
    return ss

s=input("enter string")
v=input('enter vowel')
f(s,v)

enter string bhnjmikol;
enter vowel l


'bhnjmlkll;'

## 91. Write a Python program to display calendar.

In [2]:
import calendar

year = int(input("Enter year: "))
print(calendar.calendar(year))

Enter year:  2026


                                  2026

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
          1  2  3  4                         1                         1
 5  6  7  8  9 10 11       2  3  4  5  6  7  8       2  3  4  5  6  7  8
12 13 14 15 16 17 18       9 10 11 12 13 14 15       9 10 11 12 13 14 15
19 20 21 22 23 24 25      16 17 18 19 20 21 22      16 17 18 19 20 21 22
26 27 28 29 30 31         23 24 25 26 27 28         23 24 25 26 27 28 29
                                                    30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                   1  2  3       1  2  3  4  5  6  7
 6  7  8  9 10 11 12       4  5  6  7  8  9 10       8  9 10 11 12 13 14
13 14 15 16 17 18 19      11 12 13 14 15 16 17      15 16 17 18 19 20 21
20 21 22 23 24 25 26      18 19 20 21 22 

## 92. Write a Python Program to Check Leap Year.

In [9]:
y=int(input())
if (y%400==0) or (y%4==0 and y%100==0):
    print('Leap year')
else:
    print("Not Leap year")

 2024


Not Leap year


## 93. Write a Python Program to Print all Prime Numbers in an Interval of 1-10.

In [13]:
for i in range(2,11):
    for j in range(2,i):
        if i%j==0:
            break
            print('number is not prime ',i)
            break
    else:
        print("number is prime ",i)
    

number is prime  2
number is prime  3
number is prime  5
number is prime  7


## 94. Write a Python Program to Display the multiplication Table.

In [14]:
n=int(input())
for i in range(1,11):
    print(i*n)

 6


6
12
18
24
30
36
42
48
54
60


## 95. Write a Python Program to Print the Fibonacci sequence.
```
Fibonacci sequence:
The Fibonacci sequence is a series of numbers where each number is the sum of the two
preceding ones, typically starting with 0 and 1. So, the sequence begins with 0 and 1, and
the next number is obtained by adding the previous two numbers. This pattern continues
indefinitely, generating a sequence that looks like this:
0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, and so on.
Mathematically, the Fibonacci sequence can be defined using the following recurrence
relation:
𝐹(0) = 0 𝐹(1) = 1 𝐹(𝑛) = 𝐹(𝑛 − 1) + 𝐹(𝑛 − 2)𝑓𝑜𝑟𝑛 > 1


In [20]:
def f(n):
    if n==1 or n==0:
        return n
    else:
        return f(n-1)+f(n-2)
for i in range(5):
    print(f(i))

0
1
1
2
3


## 96. Write a Python Program to Find the Sum of Natural Numbers.
```
Natural numbers are a set of positive integers that are used to count and order objects.
They are the numbers that typically start from 1 and continue indefinitely, including all the
whole numbers greater than 0. In mathematical notation, the set of natural numbers is often
denoted as "N" and can be expressed as:
𝑁 = 1, 2, 3, 4, 5, 6, 7, 8, . . .


In [24]:
s=0
for i in range(int(input())+1):
    s=s+i
s

 5


15

## 97. Write a Python Program to Add Two Matrices

In [25]:
import numpy as np
m1=np.arange(0,25).reshape(5,5)
m2=np.arange(0,25).reshape(5,5)
m1+m2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

## 98. Write a Python Program to Multiply Two Matrices.

In [26]:
import numpy as np
m1=np.arange(0,25).reshape(5,5)
m2=np.arange(0,25).reshape(5,5)
m1*m2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

## 99. Write a Python Program to Transpose a Matrix.

In [34]:
import numpy as np
m1=np.arange(0,25).reshape(5,5)
m2=np.arange(0,25).reshape(5,5)
print(m1)
m1.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 0,  5, 10, 15, 20],
       [ 1,  6, 11, 16, 21],
       [ 2,  7, 12, 17, 22],
       [ 3,  8, 13, 18, 23],
       [ 4,  9, 14, 19, 24]])

## 100. Write a Python program to print all pronic numbers between 1 and 100.
```
A pronic number, also known as an oblong number or rectangular number, is a type of
figurate number that represents a rectangle. It is the product of two consecutive integers, n
and (n + 1). Mathematically, a pronic number can be expressed as:
For example, the first few pronic numbers are:
𝑃 = 𝑛 ∗ (𝑛 + 1) 𝑛
𝑃1 = 1 ∗ (1 + 1) = 2
𝑃2 = 2 ∗ (2 + 1) = 6
𝑃3 = 3 ∗ (3 + 1) = 12
𝑃4 = 4 ∗ (4 + 1) = 20

In [36]:
for i in range(1,101):
    if i*(i+1)<=100:
        print(i*(i+1))

2
6
12
20
30
42
56
72
90
