## speed of list vs Numpy

In [1]:
x = [i for i in range (10000000)]
y = [ i for i in range(10000000,20000000)]

z = []
import time
start  =  time.time()
for i in range(len(x)):
    z.append(x[i] + y[i])
print(time.time() - start)

4.2560200691223145


In [2]:
# numpy

import numpy as np

x = np.arange(10000000)
y = np.arange(10000000,20000000)

start  =  time.time()
z = x+y
print(time.time() - start)

0.19663548469543457


## memory used for list vs numpy

In [3]:
# list

l = [i for i in range(10000000)]

import sys

sys.getsizeof(l)

89095160

In [4]:
# numpy

n = np.arange(10000000, dtype = np.int16)   #------------- memory used by numpy is less than list

sys.getsizeof(n)

20000112

## Check version of numpy

In [5]:
import numpy as np

In [6]:
print(np.__version__)

1.26.4


In [7]:
print(np.version.version)

1.26.4


## 1D Array

In [8]:
#1D Array
import numpy as np

arr_1d = np.array([1,2,3,4,5])
print("1D Array:",arr_1d)
print(type(arr_1d))

1D Array: [1 2 3 4 5]
<class 'numpy.ndarray'>


## 2D Array

In [9]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("2D Array:\n",arr_2d)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## 3D Array

In [10]:
arr_3d = np.array([[[1,2,3],
                    [4,5,6],
                    [7,8,9]],
                  
                  [[10,11,12],
                   [13,14,15],
                   [16,17,18]],

                  [[19,20,21],
                   [22,23,24],
                   [25,26,27]]])
print("3D Array:\n",arr_3d)

3D Array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [12]:
print("Shape of 1D Array:",arr_1d.shape)
print("Shape of 2D Array:",arr_2d.shape)
print("Shape of 3D Array:",arr_3d.shape)
print()
print("Dimention of 1D Array:",arr_1d.ndim)
print("Dimention of 2D Array:",arr_2d.ndim)
print("Dimention of 3D Array:",arr_3d.ndim)

Shape of 1D Array: (5,)
Shape of 2D Array: (3, 3)
Shape of 3D Array: (3, 3, 3)

Dimention of 1D Array: 1
Dimention of 2D Array: 2
Dimention of 3D Array: 3


In [13]:
print("1D Array:",arr_1d)
print("Size of 1D Array:",arr_1d.size)
print("Bytes per elements in 1D Array:",arr_1d.itemsize)
print("Total bytes of 1D Array:",arr_1d.nbytes)
print()

print("2D Array:",arr_2d)
print("Size of 2D Array:",arr_2d.size)
print("Bytes per elements in 2D Array:",arr_2d.itemsize)
print("Total bytes of 2D Array:",arr_2d.nbytes)
print()

print("3D Array:",arr_3d)
print("Size of 3D Array:",arr_3d.size)
print("Bytes per elements in 3D Array:",arr_3d.itemsize)
print("Total bytes of 3D Array:",arr_3d.nbytes)


1D Array: [1 2 3 4 5]
Size of 1D Array: 5
Bytes per elements in 1D Array: 4
Total bytes of 1D Array: 20

2D Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Size of 2D Array: 9
Bytes per elements in 2D Array: 4
Total bytes of 2D Array: 36

3D Array: [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Size of 3D Array: 27
Bytes per elements in 3D Array: 4
Total bytes of 3D Array: 108


## using fuction

In [14]:
zeros = np.zeros((2,3))
print("Array of zeros:\n",zeros)
print()

ones = np.ones((3,2))
print("Array of ones:\n",ones)
print()




Array of zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Array of ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]



In [15]:
arr3 = np.array([[1,5,2.5],[7,3,'a']])
arr3.dtype

dtype('<U32')

In [16]:
arr1d = np.arange(0,10)
print(arr1d)
print()
print(type(arr1d))
print(arr1d.shape)
print(arr1d.dtype)


[0 1 2 3 4 5 6 7 8 9]

<class 'numpy.ndarray'>
(10,)
int32


In [17]:
arr3d = np.array([[1.8,2.4,3.4],
                  [4.3,5.5,6.6],
                  [4.6,1.3,4.5]])
print(arr3d.ndim)
print(arr3d.shape)
print(arr3d.itemsize)

2
(3, 3)
8


In [18]:
arr_3d = np.full((2,2,3),0)
print(arr_3d)

print(arr_3d.ndim)
print(arr_3d.dtype)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
3
int32


In [19]:
arr =np.array([[i for i in range(1+j*3,4+j*3)] for j in range(3)],dtype = float)
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [20]:
import numpy as np
l = []
for i in range(1,5):
    int_1 = int(input("Enter:"))
    l.append(int_1)
print(np.array(l))

Enter: 6
Enter: 5
Enter: 7
Enter: 3


[6 5 7 3]


In [21]:
## Generating random number........... Uniform distirbution
import numpy as np
random_uniform = np.random.rand(5)#-------Creating 1d array
random_uniform

array([0.40880256, 0.72762262, 0.1661562 , 0.39845568, 0.46171988])

In [22]:
random_uniform.ndim

1

In [23]:
random_2d = np.random.rand(3,3) #---------Creating 2d array
random_2d

array([[0.87527546, 0.07139043, 0.37329819],
       [0.45916589, 0.16601198, 0.54007939],
       [0.9590668 , 0.75703036, 0.54848068]])

In [24]:
random_normal = np.random.randn(5)#-------Normal Distribution
random_normal

array([ 0.76628755, -0.18380463, -0.43523855, -0.28449591, -0.61509608])

In [25]:
random_2d = np.random.randn(5,5)#-------Creating normal distribution with 5 rows and 5 columns
random_2d

array([[-0.42111427, -1.59909662, -1.04249116,  1.17047216,  0.32898864],
       [-0.09250341,  0.59775351,  0.08129553, -0.22490425,  1.77815571],
       [ 0.38566004, -0.59319483,  0.53266972, -1.41180217,  1.14758455],
       [ 1.13273234, -1.2062113 ,  2.03734177, -0.03111828, -2.24870595],
       [ 0.97513686,  0.44065627, -0.01109761, -0.03868834, -0.54520861]])

In [26]:
# Generate random integer

random_integer = np.random.randint(0,10, size=5)
random_integer

array([3, 9, 4, 1, 8])

In [27]:
random_unform = np.random.uniform(10,15,5)# -----5 is the size
random_uniform

array([0.40880256, 0.72762262, 0.1661562 , 0.39845568, 0.46171988])

In [28]:
random_uniform_2d = np.random.uniform(10,50,(2,3))# 2 and 3 is the rows and columns
random_uniform_2d

array([[48.17501472, 22.56122137, 19.01746313],
       [48.42102883, 13.61438058, 38.7158728 ]])

In [29]:
random_uniform_2d[1][2]

38.71587279568996

## Indexing

In [30]:
arr_1d = np.array([10,20,30,40,50])
arr_1d

array([10, 20, 30, 40, 50])

In [31]:
arr_1d[2]

30

In [32]:
arr_1d[3]=60
arr_1d

array([10, 20, 30, 60, 50])

In [33]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr_2d[1,2]

6

In [35]:
arr_2d[0,0]=100
arr_2d

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [36]:
arr_2d[1::2]

array([[4, 5, 6]])

In [37]:
arr_2d[1]

array([4, 5, 6])

In [38]:
arr_2d[:,1]

array([2, 5, 8])

In [39]:
arr_2d[1: ,1:]

array([[5, 6],
       [8, 9]])

In [40]:
arr_23 = np.array([[1,2,3,6],[2,5,6,4],[3,8,6,5]])
arr_23

array([[1, 2, 3, 6],
       [2, 5, 6, 4],
       [3, 8, 6, 5]])

In [41]:
arr_23[1:,1:3]

array([[5, 6],
       [8, 6]])

In [42]:
arr = np.array([7,2,3,4,5])
arr[arr>2]

array([7, 3, 4, 5])

In [43]:
arr_23

array([[1, 2, 3, 6],
       [2, 5, 6, 4],
       [3, 8, 6, 5]])

In [44]:
arr_23[1]=[10,20,30,45]
arr_23

array([[ 1,  2,  3,  6],
       [10, 20, 30, 45],
       [ 3,  8,  6,  5]])

In [45]:
arr_23[:,3]=[0,0,0]
arr_23

array([[ 1,  2,  3,  0],
       [10, 20, 30,  0],
       [ 3,  8,  6,  0]])

In [46]:
arr1d = np.array([1,2,3,4,5,6,7,8,9])
arr1d[arr1d>5]=0
arr1d

array([1, 2, 3, 4, 5, 0, 0, 0, 0])

In [47]:
arr_23[1:,2:]

array([[30,  0],
       [ 6,  0]])

In [48]:
arr_23[2:,1:3]

array([[8, 6]])

In [49]:
ar1 = np.array([[1,2,3],[4,5,6]])
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
new_ar = np.insert(ar1,1,[3,3,3],axis=0)
new_ar

array([[1, 2, 3],
       [3, 3, 3],
       [4, 5, 6]])

In [51]:
new_ar[:,1:]

array([[2, 3],
       [3, 3],
       [5, 6]])

In [52]:
new_ar[2:,2:]

array([[6]])

In [53]:
new_ar[2:,0:2]

array([[4, 5]])

In [54]:
new_ar

array([[1, 2, 3],
       [3, 3, 3],
       [4, 5, 6]])

In [55]:
n = np.append(new_ar, [[3,3,3]],axis=0)
n

array([[1, 2, 3],
       [3, 3, 3],
       [4, 5, 6],
       [3, 3, 3]])

In [56]:
np= np.append(new_ar, [[3,3,3]],axis=0)
np


array([[1, 2, 3],
       [3, 3, 3],
       [4, 5, 6],
       [3, 3, 3]])

In [57]:
new_ar

array([[1, 2, 3],
       [3, 3, 3],
       [4, 5, 6]])

In [61]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.array([7, 8, 9]).reshape(-1, 1)  # Ensure b is a column vector

result = np.concatenate((a, b), axis=1)

print(result)

AttributeError: 'numpy.ndarray' object has no attribute 'array'

In [62]:
np = np.append(new_ar, [[1],[2],[3]],axis=1)
np

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [ ]:
import numpy as np
arr = np.arange(1,13)
arr

In [ ]:
reshape = np.reshape(arr,(4,3))
reshape

In [ ]:
aa = np.reshape(reshape,-1)
aa